apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kevineye/argocd-cluster-bootstrap.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true